spring:
  application:
    name: Loan-Management-System

  datasource:
    url: jdbc:mysql://localhost:3306/loan_management_system?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  kafka:
    bootstrap-servers: localhost:9092

    # Producer settings
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    # Consumer settings
    consumer:
      group-id: loan-management-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
      enable-auto-commit: false

server:
  port: 8080